// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelcellTickets.Api.Data;

#nullable disable

namespace TelcellTickets.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelcellTickets.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrganizer")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizerName")
                        .HasColumnType("text");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleAm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventFloor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventLayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventLayoutId");

                    b.ToTable("EventFloors");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasSeatingPlan")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("VenueLayoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("EventLayouts");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EventSeatBlockId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReservedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventSeatBlockId");

                    b.ToTable("EventSeats");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventSeatBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<string>("DefaultColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultDescription")
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("EventFloorId")
                        .HasColumnType("uuid");

                    b.Property<double>("RotationDeg")
                        .HasColumnType("double precision");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventFloorId");

                    b.ToTable("EventSeatBlocks");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EventFloorId")
                        .HasColumnType("uuid");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EventFloorId")
                        .IsUnique();

                    b.ToTable("EventStages");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeatBlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeatBlockId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.SeatBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<string>("DefaultColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultDescription")
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<double>("RotationDeg")
                        .HasColumnType("double precision");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueFloorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueFloorId");

                    b.ToTable("SeatBlocks");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.SeatReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventSeatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventSeatId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionId");

                    b.ToTable("SeatReservations");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CanvasX")
                        .HasColumnType("double precision");

                    b.Property<double>("CanvasY")
                        .HasColumnType("double precision");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueFloorId")
                        .HasColumnType("uuid");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VenueFloorId")
                        .IsUnique();

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventSeatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TicketTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TransferredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferredTo")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventSeatId");

                    b.HasIndex("OrderId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Sold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressAm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueFloor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueLayoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueLayoutId");

                    b.ToTable("VenueFloors");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueLayouts");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Event", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.AppUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TelcellTickets.Api.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventFloor", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.EventLayout", "EventLayout")
                        .WithMany("Floors")
                        .HasForeignKey("EventLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventLayout");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventLayout", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventSeat", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.EventSeatBlock", "EventSeatBlock")
                        .WithMany("Seats")
                        .HasForeignKey("EventSeatBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSeatBlock");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventSeatBlock", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.EventFloor", "EventFloor")
                        .WithMany("SeatBlocks")
                        .HasForeignKey("EventFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventFloor");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventStage", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.EventFloor", "EventFloor")
                        .WithOne("Stage")
                        .HasForeignKey("TelcellTickets.Api.Models.EventStage", "EventFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventFloor");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Order", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Seat", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.SeatBlock", "SeatBlock")
                        .WithMany("Seats")
                        .HasForeignKey("SeatBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatBlock");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.SeatBlock", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.VenueFloor", "VenueFloor")
                        .WithMany("SeatBlocks")
                        .HasForeignKey("VenueFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueFloor");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Stage", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.VenueFloor", "VenueFloor")
                        .WithOne("Stage")
                        .HasForeignKey("TelcellTickets.Api.Models.Stage", "VenueFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueFloor");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Ticket", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.AppUser", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AppUserId");

                    b.HasOne("TelcellTickets.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelcellTickets.Api.Models.EventSeat", "EventSeat")
                        .WithMany()
                        .HasForeignKey("EventSeatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TelcellTickets.Api.Models.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelcellTickets.Api.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("EventSeat");

                    b.Navigation("Order");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.TicketType", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueFloor", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.VenueLayout", "VenueLayout")
                        .WithMany("Floors")
                        .HasForeignKey("VenueLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueLayout");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueLayout", b =>
                {
                    b.HasOne("TelcellTickets.Api.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.AppUser", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Event", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventFloor", b =>
                {
                    b.Navigation("SeatBlocks");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventLayout", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.EventSeatBlock", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.SeatBlock", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueFloor", b =>
                {
                    b.Navigation("SeatBlocks");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TelcellTickets.Api.Models.VenueLayout", b =>
                {
                    b.Navigation("Floors");
                });
#pragma warning restore 612, 618
        }
    }
}
